# Generated by Django 5.2.1 on 2025-05-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_pendingregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingRegistration',
        ),
    ]
